/**
 * Vendor SQLite (via sql.js) into a lab, reproducibly.
 *
 *   node tools/vendor-sqljs.js labs/<lab>
 *
 * The site has no build step and no runtime dependencies, and one lab needs a
 * real database engine — there is no honest way to demonstrate a query planner
 * without one. So SQLite, compiled to WebAssembly by the sql.js project, is
 * checked into the repository rather than fetched at runtime. This script is
 * how those files are produced, so "where did this 800KB blob come from" has a
 * one-command answer.
 *
 * Three files are written:
 *
 *   vendor/sql-wasm.js            sql.js's own loader, copied byte for byte
 *   vendor/sqlite-wasm-base64.js  the .wasm binary, base64 in a plain <script>
 *   vendor/LICENSE                sql.js's MIT licence, copied verbatim
 *
 * The base64 step is the point of the whole file. Loading the .wasm the normal
 * way means fetch(), and every lab page ships `connect-src 'none'` plus a
 * network counter pinned at zero — a claim worth more than the ~200KB that
 * base64 costs over the raw binary. Handed to initSqlJs as `wasmBinary`, the
 * engine never touches the network at all.
 *
 * sql.js is MIT (Copyright (c) 2017 sql.js authors). SQLite itself is public
 * domain. Neither is covered by this repository's all-rights-reserved LICENSE,
 * and the vendored copies keep their own notices — see vendor/LICENSE and the
 * banner this script writes into each generated file.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'node_modules', 'sql.js');

const target = process.argv[2];
if (!target) {
  console.error('usage: node tools/vendor-sqljs.js labs/<lab>');
  process.exit(1);
}

const pkg = JSON.parse(fs.readFileSync(path.join(SRC, 'package.json'), 'utf8'));
/* path.join would quietly produce nonsense for an absolute argument, so the
   target is resolved against the repository root and then checked to be inside
   it — this script writes files, and a typo should stop it rather than steer it. */
const outDir = path.join(path.resolve(ROOT, target), 'vendor');
if (!outDir.startsWith(ROOT + path.sep)) {
  console.error('refusing: ' + target + ' resolves outside the repository');
  process.exit(1);
}
fs.mkdirSync(outDir, { recursive: true });

const banner = (what) => `/*!
 * ${what}
 *
 * THIRD-PARTY CODE. Not covered by this repository's LICENSE.
 * sql.js ${pkg.version} — MIT, Copyright (c) 2017 sql.js authors.
 * SQLite itself is in the public domain.
 * Full licence text: ./LICENSE  ·  Upstream: https://github.com/sql-js/sql.js
 *
 * Generated by tools/vendor-sqljs.js — do not edit by hand.
 */
`;

/* The loader is copied verbatim; only a banner is prepended, so a reader can
   diff it against the published package and see nothing was slipped in. */
const loaderSrc = fs.readFileSync(path.join(SRC, 'dist', 'sql-wasm.js'), 'utf8');
fs.writeFileSync(
  path.join(outDir, 'sql-wasm.js'),
  banner('sql.js loader, copied byte for byte from dist/sql-wasm.js') + loaderSrc
);

const wasm = fs.readFileSync(path.join(SRC, 'dist', 'sql-wasm.wasm'));
fs.writeFileSync(
  path.join(outDir, 'sqlite-wasm-base64.js'),
  banner('SQLite compiled to WebAssembly, base64-encoded from dist/sql-wasm.wasm') +
  '/* Decoded by the lab and handed to initSqlJs({wasmBinary}), so the engine\n' +
  '   loads without a single network request. */\n' +
  'var SQLITE_WASM_BASE64 = "' + wasm.toString('base64') + '";\n'
);

fs.copyFileSync(path.join(SRC, 'LICENSE'), path.join(outDir, 'LICENSE'));

const kb = (p) => (fs.statSync(path.join(outDir, p)).size / 1024).toFixed(0) + 'KB';
console.log('sql.js ' + pkg.version + ' vendored into ' + target + '/vendor/');
console.log('  sql-wasm.js            ' + kb('sql-wasm.js'));
console.log('  sqlite-wasm-base64.js  ' + kb('sqlite-wasm-base64.js') + '  (raw wasm ' + (wasm.length / 1024).toFixed(0) + 'KB)');
console.log('  LICENSE                ' + kb('LICENSE'));
