/*!
 * Buku — part of the biassp.github.io portfolio
 * Copyright (c) 2026 Bias Satrio Putra. All rights reserved.
 * Not open source. Readable for evaluation only. See /LICENSE.
 * https://biassp.github.io/
 */
/* Buku — seed.js
 * One financial year of a small trading business, built from a single seed
 * integer. Nothing here is real: not the entity, not the NPWP, not the bank
 * account, not one rupiah of any figure. Every number is generated by the
 * mulberry32 PRNG in domain.js, so the same book appears on every load in every
 * browser and the totals quoted in the README can be checked against the
 * screen.
 *
 * Three things about this file are load-bearing rather than decorative.
 *
 * 1. THE OPENING BALANCE IS INTERNALLY CONSISTENT. Accumulated depreciation at
 *    1 January is not a plausible-looking number typed into the opening entry —
 *    it is DERIVED by summing each asset's depreciation schedule up to
 *    2024-12, from the same jadwalPenyusutan() the adjusting entry uses. Type it
 *    in by hand and the fixed-asset note stops agreeing with the balance sheet
 *    in the second year, which is exactly the sort of thing that survives a demo
 *    and not an audit. Saldo Laba is the single balancing figure, computed, so
 *    the opening entry balances by arithmetic rather than by luck.
 *
 * 2. THE ADJUSTING ENTRIES ARE NOT POSTED. The seeded book is a year of ordinary
 *    transactions and nothing else, which is what a real book looks like on 31
 *    December before the accountant starts. The four adjustment types are
 *    proposals sitting in the Penyesuaian tab, computed from the registers, and
 *    the visitor posts them. That makes "neraca saldo sebelum / setelah
 *    penyesuaian" two genuinely different columns instead of the same numbers
 *    under two headings. The closing entry is likewise left for the visitor.
 *
 * 3. THE PPN SETTLEMENT USES LIVE BALANCES. Each month's settlement reads the
 *    actual PPN Masukan and PPN Keluaran balances out of the half-built book and
 *    offsets them, rather than assuming what they should be. If the sales and
 *    purchase generators drift, the settlement drifts with them and the tax
 *    accounts still zero out — which is why the PPN position on screen agrees
 *    with the ledger to the rupiah instead of approximately.
 */
(function (root) {
  'use strict';

  var D = root.BUKU_DOMAIN;
  var L = root.BUKU_LEDGER;
  var S = {};
  root.BUKU_SEED = S;

  S.SEED = 8613537;
  S.TAHUN = '2025';
  S.AWAL = '2025-01-01';
  S.AKHIR = '2025-12-31';
  S.TGL_SALDO_AWAL = '2024-12-31';
  /* Jan–Jun are locked. Two full quarters that have been reported and can no
   * longer be touched, so the period lock is something a visitor bumps into
   * rather than reads about. */
  S.TERKUNCI = ['2025-01', '2025-02', '2025-03', '2025-04', '2025-05', '2025-06'];

  /* The entity. Fabricated, and fabricated in ways that cannot collide with a
   * real one: the NPWP starts 99, a category prefix DJP has never issued, and
   * the bank account is in the 0000-reserved test range. */
  S.PROFIL = {
    nama: 'UD Sinar Kalibata',
    bentuk: 'Usaha Dagang perorangan',
    bidang: 'Perdagangan alat dan perlengkapan listrik, dengan jasa perakitan panel kecil',
    alamat: 'Jalan Contoh Nomor 00, Kelurahan Fiktif, Jakarta Selatan',
    npwp: '99.876.543.2-001.000',
    npwpCatatan: 'Awalan 99 tidak pernah diterbitkan DJP — nomor ini tidak bisa menunjuk wajib pajak mana pun.',
    bank: 'Rekening 0000-1234-5678 (rentang uji, bukan rekening yang bisa dituju)',
    pkp: true,
    pkpCatatan: 'Dikukuhkan sebagai PKP atas permintaan sendiri. Peredaran bruto masih di bawah Rp 4,8 miliar, ' +
      'jadi pengukuhan PKP tidak wajib — tetapi pembeli korporatnya meminta faktur pajak, dan itu alasan ' +
      'paling umum sebuah UMKM memilih jadi PKP lebih awal. Konsekuensinya: PPh-nya final 0,5% (PP 55/2022) ' +
      'sekaligus wajib memungut dan melaporkan PPN.',
    standar: 'SAK EMKM',
    pemilik: 'Pemilik tunggal (perorangan)',
    /* Stated OUTRIGHT, because the whole PPh-final computation turns on it: an
     * orang pribadi on the 0,5% regime does not pay on the first Rp 500 juta of
     * a tax year's turnover (PP 55/2022 pasal 60 ayat 2), a badan does. This
     * entity is an orang pribadi, so the exemption applies and it is not
     * optional. */
    wp: 'orang pribadi',
    pphFinalBebas: true,
    pphFinalBebasCatatan: 'Sebagai wajib pajak ORANG PRIBADI, peredaran bruto Rp 500.000.000 pertama dalam ' +
      'satu tahun pajak tidak dikenai PPh (PP 55/2022 Pasal 60 ayat 2). Bukan pilihan dan bukan pengurang ' +
      'pajak: ia sepotong dasar pengenaan yang tidak pernah masuk hitungan, dipakai kumulatif oleh masa-masa ' +
      'paling awal, dan berulang setiap tahun pajak. Sebuah badan (PT atau CV) tidak mendapat pembebasan ini.'
  };

  function ribu(n) { return D.mul(D.divRound(n, 1000), 1000); }
  function juta(n) { return D.mul(n, 1000000); }

  /* ======================================================== register aset */

  function registerAset() {
    var aset = [
      {
        id: 'AT-01', nama: 'Peralatan toko — rak, meja kasir, alat ukur',
        akunAset: '1601', akunAkum: '1602', akunBeban: '5204',
        harga: juta(96), residu: juta(6), umurBulan: 60, mulai: '2023-01',
        metode: 'Garis lurus (straight line)',
        catatan: 'Diperoleh sebelum tahun buku ini; akumulasi penyusutan pembukanya dihitung dari jadwal, bukan diisi manual.'
      },
      {
        id: 'AT-02', nama: 'Kendaraan pengangkut — pikap boks',
        akunAset: '1611', akunAkum: '1612', akunBeban: '5204',
        harga: juta(245), residu: juta(25), umurBulan: 96, mulai: '2023-07',
        metode: 'Garis lurus (straight line)',
        catatan: 'Umur 8 tahun. Dasar penyusutan Rp 220.000.000 tidak habis dibagi 96, jadi sisa rupiahnya ' +
          'dibagikan oleh alokasi() dan jadwalnya tetap tutup persis di Rp 220.000.000.'
      },
      {
        id: 'AT-03', nama: 'Peralatan toko tambahan — rak gudang dan tangga',
        akunAset: '1601', akunAkum: '1602', akunBeban: '5204',
        harga: juta(48), residu: juta(3), umurBulan: 60, mulai: '2025-05',
        metode: 'Garis lurus (straight line)',
        catatan: 'Dibeli Mei 2025, jadi hanya delapan bulan penyusutan yang masuk tahun ini — arus kas investasinya ' +
          'ada di laporan arus kas, PPN masukannya dikreditkan.'
      }
    ];
    aset.forEach(function (a) {
      a.jadwal = D.jadwalPenyusutan(a);
      a.akumAwal = D.akumSampai(a.jadwal, '2024-12');
      a.penyusutanTahun = D.penyusutanRentang(a.jadwal, S.TAHUN + '-01', S.TAHUN + '-12');
    });
    return aset;
  }

  /* ============================================== register dibayar di muka */

  function registerMuka() {
    return [
      {
        id: 'DM-01', nama: 'Sewa kios 12 bulan, dibayar di muka',
        akunMuka: '1401', akunBeban: '5202', jumlah: juta(36), mulai: '2025-07', bulan: 12,
        tglBayar: '2025-07-01', kasDari: '1102',
        catatan: 'Sewa dari pemilik kios perorangan non-PKP, jadi tidak ada PPN masukan atasnya. Enam bulan ' +
          'terpakai sampai 31 Desember, enam bulan sisanya masih aset.'
      },
      {
        id: 'DM-02', nama: 'Asuransi kendaraan dan persediaan 12 bulan',
        akunMuka: '1402', akunBeban: '5205', jumlah: juta(12), mulai: '2025-09', bulan: 12,
        tglBayar: '2025-09-01', kasDari: '1102',
        catatan: 'Empat bulan terpakai sampai 31 Desember.'
      }
    ];
  }

  /* ========================================= register pendapatan ditangguhkan */

  function registerTangguh() {
    return [
      {
        id: 'PD-01', nama: 'Kontrak perakitan panel 6 bulan, dibayar di muka pelanggan',
        akunTangguh: '2103', akunPendapatan: '4102', jumlah: juta(24), mulai: '2025-11', bulan: 6,
        tglTerima: '2025-11-10', kasKe: '1102',
        /* Faktur pajak terbit saat pembayaran diterima, bukan saat jasanya selesai —
         * itu aturan saat terutangnya PPN untuk pembayaran di muka, dan alasan
         * PPN keluaran di sini muncul lebih dulu daripada pendapatannya. */
        ppnSaatTerima: true,
        catatan: 'Dua bulan (November–Desember) sudah dikerjakan pada 31 Desember; empat bulan sisanya masih utang jasa.'
      }
    ];
  }

  /* ================================================= register pinjaman */

  /* The loan register. It exists for one reason: so that the CURRENT PORTION of
   * a term loan is derived rather than typed. Without a register there is no way
   * to know how much of a Rp 60.000.000 balance falls due within twelve months,
   * and a balance sheet that puts all of it under liabilitas jangka panjang is
   * wrong by the whole amount whenever the tenor is short — which here it is:
   * Rp 5.000.000 a month against Rp 60.000.000 outstanding is exactly twelve
   * more instalments, so 100% of it is current at 31 December 2025.
   *
   * pokokAwal is the balance at the opening date, and it is split there too: the
   * opening balance sheet carried the same defect, and an opening balance sheet
   * that is only approximately classified is not a starting point, it is a
   * second thing to fix later. */
  function registerPinjaman(angsuran) {
    return [
      {
        id: 'PJ-01', nama: 'Kredit investasi bank — pembelian kendaraan pengangkut',
        akunPokok: '2201', akunLancar: '2106', akunKas: '1102', akunBunga: '5208',
        pokokAwal: juta(120), angsuran: angsuran, tglAngsur: 5,
        catatan: 'Angsuran pokok Rp 5.000.000 setiap tanggal 5, tanpa jeda. Pada 31 Desember 2025 sisanya ' +
          'Rp 60.000.000 — tepat dua belas angsuran lagi, jadi SELURUHNYA jatuh tempo dalam dua belas bulan ' +
          'dan seluruhnya liabilitas jangka pendek.'
      }
    ];
  }

  /* ================================================== register akrual */

  function registerAkrual(gajiBulanan, bungaBulanan, listrikDes) {
    return [
      {
        id: 'AK-01', nama: 'Gaji Desember 2025, dibayar 5 Januari 2026',
        akunBeban: '5201', akunUtang: '2102', jumlah: gajiBulanan, periode: '2025-12',
        catatan: 'Bebannya milik Desember walaupun kasnya keluar Januari. Tanpa jurnal ini laba Desember terlalu besar ' +
          'dan liabilitasnya hilang dari neraca.'
      },
      {
        id: 'AK-02', nama: 'Bunga pinjaman bank Desember 2025',
        akunBeban: '5208', akunUtang: '2102', jumlah: bungaBulanan, periode: '2025-12',
        catatan: 'Bunga bulan Januari sampai November sudah dibayar tunai; yang Desember baru didebet bank awal Januari.'
      },
      {
        id: 'AK-03', nama: 'Tagihan listrik dan air Desember 2025',
        akunBeban: '5203', akunUtang: '2102', jumlah: listrikDes, periode: '2025-12',
        catatan: 'Tagihannya terbit Januari untuk pemakaian Desember.'
      }
    ];
  }

  /* ================================================================ build */

  S.build = function (opts) {
    opts = opts || {};
    var rnd = D.rng(opts.seed === undefined ? S.SEED : opts.seed);
    var buku = L.buatBuku();

    var aset = registerAset();
    var muka = registerMuka();
    var tangguh = registerTangguh();
    var pinjaman = null;         // dibentuk setelah ANGSUR diketahui

    var GAJI = juta(28);              // gaji bulanan tetap
    var BUNGA = ribu(950000);         // bunga pinjaman bulanan
    var ANGSUR = juta(5);             // angsuran pokok bulanan
    pinjaman = registerPinjaman(ANGSUR);
    var MODAL_AWAL = juta(400);
    var akrual = null;                // dibentuk setelah listrik Desember diketahui

    function post(spec) {
      spec.sumber = 'seed';
      spec.oleh = spec.oleh || 'seed';
      spec.peran = spec.peran || 'akuntan';
      return L.tambah(buku, spec, { izinTerkunci: true });
    }

    /* ------------------------------------------------------- saldo awal */

    var akumPeralatan = 0, akumKendaraan = 0;
    aset.forEach(function (a) {
      if (a.akunAkum === '1602') akumPeralatan = D.add(akumPeralatan, a.akumAwal);
      else akumKendaraan = D.add(akumKendaraan, a.akumAwal);
    });

    /* Loan split at the opening date, from the register — not typed. */
    var pokokAwal = pinjaman.reduce(function (t, k) { return D.add(t, k.pokokAwal); }, 0);
    var bagianLancarAwal = pinjaman.reduce(function (t, k) {
      return D.add(t, Math.min(k.pokokAwal, D.mul(k.angsuran, 12)));
    }, 0);

    var awalDebit = [
      { akun: '1101', jumlah: juta(24), catatan: 'kas di tangan' },
      { akun: '1102', jumlah: juta(186), catatan: 'giro operasional' },
      { akun: '1201', jumlah: ribu(142500000), catatan: 'piutang 17 pelanggan' },
      { akun: '1301', jumlah: juta(318), catatan: 'persediaan barang dagang' },
      { akun: '1601', jumlah: juta(96), catatan: 'peralatan toko (AT-01)' },
      { akun: '1611', jumlah: juta(245), catatan: 'kendaraan pengangkut (AT-02)' }
    ];
    var awalKreditTetap = [
      { akun: '1602', jumlah: akumPeralatan, catatan: 'akumulasi penyusutan AT-01 s.d. Des 2024, dari jadwal' },
      { akun: '1612', jumlah: akumKendaraan, catatan: 'akumulasi penyusutan AT-02 s.d. Des 2024, dari jadwal' },
      { akun: '2101', jumlah: ribu(168400000), catatan: 'utang ke sembilan supplier' },
      /* The term loan, SPLIT at the opening date rather than dumped into the
       * non-current account. Rp 120.000.000 outstanding at twelve instalments of
       * Rp 5.000.000 a year means Rp 60.000.000 falls due during 2025 and is
       * current; the rest is not. The split comes from the register, so it cannot
       * drift away from the repayment schedule the seed actually posts. */
      { akun: '2106', jumlah: bagianLancarAwal, catatan: 'bagian pinjaman investasi yang jatuh tempo dalam 12 bulan (12 × ' + D.rupiah(ANGSUR) + ')' },
      { akun: '2201', jumlah: pokokAwal - bagianLancarAwal, catatan: 'sisa pinjaman investasi di luar 12 bulan ke depan' },
      { akun: '3101', jumlah: MODAL_AWAL, catatan: 'modal disetor pemilik' }
    ];
    var totalD = awalDebit.reduce(function (s, r) { return D.add(s, r.jumlah); }, 0);
    var totalKTetap = awalKreditTetap.reduce(function (s, r) { return D.add(s, r.jumlah); }, 0);
    /* Saldo Laba is the plug — and it is the ONLY plug in the whole book, it
     * exists on the opening entry alone, and it is computed rather than guessed,
     * so the opening entry balances exactly. Every subsequent entry balances on
     * its own terms. */
    var saldoLabaAwal = totalD - totalKTetap;
    if (saldoLabaAwal <= 0) throw new Error('Saldo laba pembuka tidak positif — angka neraca pembuka perlu ditinjau.');

    var barisAwal = [];
    awalDebit.forEach(function (r) { barisAwal.push({ akun: r.akun, d: r.jumlah, k: 0, catatan: r.catatan }); });
    awalKreditTetap.forEach(function (r) { barisAwal.push({ akun: r.akun, d: 0, k: r.jumlah, catatan: r.catatan }); });
    barisAwal.push({ akun: '3201', d: 0, k: saldoLabaAwal, catatan: 'saldo laba akumulasi sampai 31 Des 2024 (angka penyeimbang)' });

    post({
      tgl: S.TGL_SALDO_AWAL, jenis: 'saldo-awal',
      memo: 'Neraca pembuka per 31 Desember 2024',
      baris: barisAwal
    });

    /* -------------------------------------------------- siklus bulanan */

    var persediaan = juta(318);
    var brutoKumulatif = 0;      // peredaran bruto tahun berjalan, untuk pembebasan Rp 500 juta
    var ringkasBulan = [];
    var jejakKoreksi = null, jejakPembalik = null;

    for (var m = 1; m <= 12; m++) {
      var per = S.TAHUN + '-' + String(m).padStart(2, '0');
      var hariAkhir = D.hariDalamBulan(+S.TAHUN, m);
      var spec = [];   // { tgl, urut, fn } — dikumpulkan lalu diurut per tanggal

      function tgl(d) { return per + '-' + String(Math.min(d, hariAkhir)).padStart(2, '0'); }

      /* --- penjualan barang dagang -------------------------------------- */
      var nJual = D.acakInt(rnd, 8, 13);
      var jualBulan = [], hppBulan = 0, dppBulan = 0;
      for (var s = 0; s < nJual; s++) {
        var dpp = ribu(D.acakInt(rnd, 9000000, 33000000));
        var rasio = D.acakInt(rnd, 6750, 7450);          // HPP 67,5%–74,5% dari DPP
        var hpp = D.divRound(D.mul(dpp, rasio), 10000);
        var hari = D.acakInt(rnd, 4, Math.min(27, hariAkhir));
        var tunai = rnd() < 0.45;
        /* Cash sales are banked the same day, so the petty-cash account holds
         * petty cash and nothing else. Routing every small cash sale into 1101
         * instead left the till carrying Rp 400 juta by December — arithmetically
         * fine, and obviously nonsense to anyone who has run a shop. */
        var akunKas = '1102';
        jualBulan.push({ dpp: dpp, hpp: hpp, hari: hari, tunai: tunai, akunKas: akunKas });
        hppBulan = D.add(hppBulan, hpp);
        dppBulan = D.add(dppBulan, dpp);
      }

      /* --- jasa perakitan ---------------------------------------------- */
      var nJasa = D.acakInt(rnd, 1, 2);
      var jasaBulan = [];
      for (var jj = 0; jj < nJasa; jj++) {
        var dppJasa = ribu(D.acakInt(rnd, 3500000, 11000000));
        jasaBulan.push({ dpp: dppJasa, hari: D.acakInt(rnd, 6, Math.min(26, hariAkhir)), tunai: rnd() < 0.6 });
      }

      /* --- pembelian persediaan ---------------------------------------- */
      /* Purchases are sized off the month's cost of sales plus a small drift, so
       * inventory neither runs to zero nor climbs to something a shop this size
       * could not finance. */
      var belanja = D.add(hppBulan, ribu(D.acakInt(rnd, -18000000, 26000000)));
      if (belanja < juta(40)) belanja = juta(40);
      var nBeli = D.acakInt(rnd, 3, 5);
      var bobot = [];
      for (var bi = 0; bi < nBeli; bi++) bobot.push(D.acakInt(rnd, 6, 16));
      var bagian = D.alokasi(belanja, bobot);
      var beliBulan = [];
      for (bi = 0; bi < nBeli; bi++) {
        var nilai = ribu(bagian[bi]);
        if (nilai <= 0) continue;
        beliBulan.push({ dpp: nilai, hari: D.acakInt(rnd, 2, Math.min(12, hariAkhir)), tunai: rnd() < 0.25 });
      }

      /* --- daftar entri, dikumpulkan lalu diurut per tanggal ----------- */
      var daftar = [];

      beliBulan.forEach(function (b, idx) {
        var ppn = D.ppnDari(b.dpp);
        var bruto = D.add(b.dpp, ppn);
        daftar.push({
          hari: b.hari, urut: 10 + idx,
          spec: {
            tgl: tgl(b.hari), jenis: 'umum',
            memo: 'Pembelian barang dagang dari supplier' + (b.tunai ? ', dibayar bank' : ', kredit 30 hari'),
            baris: [
              { akun: '1301', d: b.dpp, k: 0, catatan: 'persediaan masuk' },
              { akun: '1501', d: ppn, k: 0, catatan: 'PPN masukan, faktur diterima' },
              { akun: b.tunai ? '1102' : '2101', d: 0, k: bruto, catatan: b.tunai ? 'transfer ke supplier' : 'utang usaha' }
            ]
          },
          efek: function () { persediaan = D.add(persediaan, b.dpp); }
        });
      });

      jualBulan.forEach(function (j, idx) {
        var ppn = D.ppnDari(j.dpp);
        var bruto = D.add(j.dpp, ppn);
        daftar.push({
          hari: j.hari, urut: 40 + idx * 2,
          spec: {
            tgl: tgl(j.hari), jenis: 'umum',
            memo: 'Penjualan barang dagang' + (j.tunai ? ' tunai' : ' kredit'),
            baris: [
              { akun: j.tunai ? j.akunKas : '1201', d: bruto, k: 0, catatan: j.tunai ? 'diterima' : 'piutang usaha' },
              { akun: '4101', d: 0, k: j.dpp, catatan: 'DPP penjualan' },
              { akun: '2104', d: 0, k: ppn, catatan: 'PPN keluaran 11% (tarif 12% atas DPP nilai lain 11/12)' }
            ]
          }
        });
        daftar.push({
          hari: j.hari, urut: 41 + idx * 2,
          spec: {
            tgl: tgl(j.hari), jenis: 'umum',
            memo: 'Harga pokok penjualan atas penjualan hari itu (sistem perpetual)',
            baris: [
              { akun: '5101', d: j.hpp, k: 0, catatan: 'HPP' },
              { akun: '1301', d: 0, k: j.hpp, catatan: 'persediaan keluar' }
            ]
          },
          efek: function () { persediaan = persediaan - j.hpp; }
        });
      });

      jasaBulan.forEach(function (jz, idx) {
        var ppn = D.ppnDari(jz.dpp);
        daftar.push({
          hari: jz.hari, urut: 70 + idx,
          spec: {
            tgl: tgl(jz.hari), jenis: 'umum',
            memo: 'Pendapatan jasa perakitan panel',
            baris: [
              { akun: jz.tunai ? '1102' : '1201', d: D.add(jz.dpp, ppn), k: 0 },
              { akun: '4102', d: 0, k: jz.dpp, catatan: 'jasa perakitan' },
              { akun: '2104', d: 0, k: ppn, catatan: 'PPN keluaran' }
            ]
          }
        });
      });

      /* --- penagihan piutang ------------------------------------------- */
      daftar.push({
        hari: D.acakInt(rnd, 8, 14), urut: 80,
        dinamis: function (tglIni) {
          var saldo = L.saldoAkun(buku, '1201', { sampai: tglIni }).saldo;
          var target = ribu(D.acakInt(rnd, 95000000, 175000000));
          var jumlah = Math.min(saldo, target);
          if (jumlah <= 0) return null;
          return {
            tgl: tglIni, jenis: 'umum', memo: 'Penerimaan pelunasan piutang beberapa pelanggan',
            baris: [
              { akun: '1102', d: jumlah, k: 0, catatan: 'transfer masuk' },
              { akun: '1201', d: 0, k: jumlah, catatan: 'piutang lunas' }
            ]
          };
        }
      });
      daftar.push({
        hari: D.acakInt(rnd, 20, Math.min(26, hariAkhir)), urut: 81,
        dinamis: function (tglIni) {
          var saldo = L.saldoAkun(buku, '1201', { sampai: tglIni }).saldo;
          var target = ribu(D.acakInt(rnd, 40000000, 90000000));
          var jumlah = Math.min(saldo, target);
          if (jumlah <= 0) return null;
          return {
            tgl: tglIni, jenis: 'umum', memo: 'Penerimaan pelunasan piutang gelombang kedua',
            baris: [
              { akun: '1102', d: jumlah, k: 0 },
              { akun: '1201', d: 0, k: jumlah }
            ]
          };
        }
      });

      /* --- pembayaran utang usaha -------------------------------------- */
      daftar.push({
        hari: D.acakInt(rnd, 15, Math.min(24, hariAkhir)), urut: 90,
        dinamis: function (tglIni) {
          var saldo = L.saldoAkun(buku, '2101', { sampai: tglIni }).saldo;
          var target = ribu(D.acakInt(rnd, 110000000, 190000000));
          var jumlah = Math.min(saldo, target);
          if (jumlah <= 0) return null;
          return {
            tgl: tglIni, jenis: 'umum', memo: 'Pembayaran utang usaha ke supplier',
            baris: [
              { akun: '2101', d: jumlah, k: 0, catatan: 'utang dilunasi' },
              { akun: '1102', d: 0, k: jumlah, catatan: 'transfer keluar' }
            ]
          };
        }
      });

      /* --- beban operasional rutin ------------------------------------- */
      var listrik = ribu(D.acakInt(rnd, 2600000, 4400000));
      var kirim = ribu(D.acakInt(rnd, 1800000, 3900000));
      var adminBank = ribu(D.acakInt(rnd, 85000, 190000));

      if (m < 12) {
        daftar.push({
          hari: 25, urut: 100,
          spec: {
            tgl: tgl(25), jenis: 'umum', memo: 'Pembayaran gaji dan upah karyawan',
            baris: [
              { akun: '5201', d: GAJI, k: 0, catatan: '4 karyawan tetap' },
              { akun: '1102', d: 0, k: GAJI }
            ]
          }
        });
      }
      /* December's electricity bill arrives in January, so December has no cash
       * utilities payment — it has an accrual instead, which is AK-03. */
      if (m < 12) {
        daftar.push({
          hari: 20, urut: 101,
          spec: {
            tgl: tgl(20), jenis: 'umum', memo: 'Pembayaran listrik, air dan telepon',
            baris: [
              { akun: '5203', d: listrik, k: 0 },
              { akun: '1101', d: 0, k: listrik }
            ]
          }
        });
      }
      daftar.push({
        hari: 22, urut: 102,
        spec: {
          tgl: tgl(22), jenis: 'umum', memo: 'Beban pengiriman barang ke pelanggan',
          baris: [
            { akun: '5207', d: kirim, k: 0 },
            { akun: '1101', d: 0, k: kirim }
          ]
        }
      });
      daftar.push({
        hari: hariAkhir, urut: 103,
        spec: {
          tgl: tgl(hariAkhir), jenis: 'umum', memo: 'Biaya administrasi bank bulanan',
          baris: [
            { akun: '5206', d: adminBank, k: 0 },
            { akun: '1102', d: 0, k: adminBank }
          ]
        }
      });

      /* --- angsuran dan bunga pinjaman -------------------------------- */
      daftar.push({
        hari: 5, urut: 104,
        spec: {
          tgl: tgl(5), jenis: 'umum', memo: 'Angsuran pokok pinjaman bank' + (m < 12 ? ' dan bunga bulan ini' : ' (bunga Desember baru didebet Januari)'),
          baris: m < 12
            ? [
              /* The instalment retires the CURRENT portion. It is 2106 that runs
               * down through the year and 2201 that is reclassified into it at
               * year end — the movement a loan amortisation table shows, and the
               * reason the balance sheet's current/non-current split stays true
               * all year rather than only on 31 December. */
              { akun: '2106', d: ANGSUR, k: 0, catatan: 'pokok — bagian lancar' },
              { akun: '5208', d: BUNGA, k: 0, catatan: 'bunga' },
              { akun: '1102', d: 0, k: D.add(ANGSUR, BUNGA) }
            ]
            : [
              { akun: '2106', d: ANGSUR, k: 0, catatan: 'pokok — bagian lancar' },
              { akun: '1102', d: 0, k: ANGSUR }
            ]
        }
      });

      /* --- kas kecil diisi dari bank ---------------------------------- */
      daftar.push({
        hari: 3, urut: 105,
        spec: {
          tgl: tgl(3), jenis: 'umum', memo: 'Pengisian kas kecil dari giro',
          baris: [
            { akun: '1101', d: juta(6), k: 0 },
            { akun: '1102', d: 0, k: juta(6) }
          ]
        }
      });

      /* --- kejadian sekali setahun ------------------------------------ */
      if (m === 3) {
        daftar.push({
          hari: 12, urut: 110,
          spec: {
            tgl: tgl(12), jenis: 'umum', memo: 'Setoran modal tambahan dari pemilik',
            baris: [
              { akun: '1102', d: juta(100), k: 0 },
              { akun: '3101', d: 0, k: juta(100), catatan: 'tambahan modal disetor' }
            ]
          }
        });
      }
      if (m === 5) {
        var asetBaru = aset[2];
        var ppnAset = D.ppnDari(asetBaru.harga);
        daftar.push({
          hari: 6, urut: 111,
          spec: {
            tgl: tgl(6), jenis: 'umum', memo: 'Pembelian peralatan toko tambahan (AT-03), tunai lewat bank',
            baris: [
              { akun: '1601', d: asetBaru.harga, k: 0, catatan: 'rak gudang dan tangga' },
              { akun: '1501', d: ppnAset, k: 0, catatan: 'PPN masukan atas perolehan aset' },
              { akun: '1102', d: 0, k: D.add(asetBaru.harga, ppnAset) }
            ]
          }
        });
      }
      if (m === 7) {
        var dm = muka[0];
        daftar.push({
          hari: 1, urut: 112,
          spec: {
            tgl: dm.tglBayar, jenis: 'umum', memo: 'Pembayaran sewa kios 12 bulan di muka (Juli 2025 – Juni 2026)',
            baris: [
              { akun: dm.akunMuka, d: dm.jumlah, k: 0, catatan: 'belum menjadi beban' },
              { akun: dm.kasDari, d: 0, k: dm.jumlah }
            ]
          }
        });
      }
      if (m === 9) {
        var dm2 = muka[1];
        daftar.push({
          hari: 1, urut: 113,
          spec: {
            tgl: dm2.tglBayar, jenis: 'umum', memo: 'Pembayaran premi asuransi 12 bulan di muka (Sept 2025 – Ags 2026)',
            baris: [
              { akun: dm2.akunMuka, d: dm2.jumlah, k: 0 },
              { akun: dm2.kasDari, d: 0, k: dm2.jumlah }
            ]
          }
        });
      }
      if (m === 11) {
        var pd = tangguh[0];
        var ppnPd = D.ppnDari(pd.jumlah);
        daftar.push({
          hari: 10, urut: 114,
          spec: {
            tgl: pd.tglTerima, jenis: 'umum',
            memo: 'Uang muka kontrak perakitan panel 6 bulan diterima — faktur pajak terbit saat pembayaran diterima',
            baris: [
              { akun: pd.kasKe, d: D.add(pd.jumlah, ppnPd), k: 0 },
              { akun: pd.akunTangguh, d: 0, k: pd.jumlah, catatan: 'belum menjadi pendapatan' },
              { akun: '2104', d: 0, k: ppnPd, catatan: 'PPN keluaran atas uang muka' }
            ]
          }
        });
      }
      /* Owner's drawings, once a quarter. Financing outflow, and the reason the
       * equity statement has a prive line to subtract. */
      if (m === 3 || m === 6 || m === 9 || m === 12) {
        daftar.push({
          hari: 28, urut: 115,
          spec: {
            tgl: tgl(28), jenis: 'umum', memo: 'Prive pemilik (pengambilan untuk keperluan pribadi)',
            baris: [
              { akun: '3102', d: juta(25), k: 0, catatan: 'pengambilan pemilik' },
              { akun: '1102', d: 0, k: juta(25) }
            ]
          }
        });
      }
      if (m === 4 || m === 10) {
        var jasaGiro = ribu(D.acakInt(rnd, 240000, 690000));
        daftar.push({
          hari: hariAkhir, urut: 116,
          spec: {
            tgl: tgl(hariAkhir), jenis: 'umum', memo: 'Jasa giro bank (pendapatan lain-lain)',
            baris: [
              { akun: '1102', d: jasaGiro, k: 0 },
              { akun: '4901', d: 0, k: jasaGiro }
            ]
          }
        });
      }

      /* --- entri yang sengaja salah, lalu dikoreksi ------------------- */
      /* August: the electricity payment is entered as 4.500.000 when the bill was
       * 1.450.000 — a transposition anyone who has done data entry will
       * recognise. It is corrected in September, and the correction is a
       * reversal plus a replacement, so all three documents stay in the book. */
      if (m === 8) {
        daftar.push({
          hari: 20, urut: 120,
          tandaiSalah: true,
          spec: {
            tgl: tgl(20), jenis: 'umum', memo: 'Pembayaran listrik, air dan telepon (angka salah entri: 4.500.000)',
            baris: [
              { akun: '5203', d: juta(0) + 4500000, k: 0 },
              { akun: '1101', d: 0, k: 4500000 }
            ]
          }
        });
      }
      /* October: a service invoice keyed twice. Reversed two days later, and the
       * reversal is a jurnal pembalik referencing the duplicate — the duplicate
       * is not deleted. */
      if (m === 10) {
        daftar.push({
          hari: 14, urut: 121,
          tandaiGanda: true,
          spec: {
            tgl: tgl(14), jenis: 'umum', memo: 'Pendapatan jasa perakitan — TERNYATA GANDA, sudah dicatat di nota lain',
            baris: [
              { akun: '1201', d: 7770000, k: 0 },
              { akun: '4102', d: 0, k: 7000000 },
              { akun: '2104', d: 0, k: 770000 }
            ]
          }
        });
      }

      /* --- posting, urut per tanggal ---------------------------------- */
      daftar.sort(function (a, b) {
        var ta = a.spec ? a.spec.tgl : tgl(a.hari);
        var tb = b.spec ? b.spec.tgl : tgl(b.hari);
        if (ta !== tb) return ta < tb ? -1 : 1;
        return a.urut - b.urut;
      });

      for (var di = 0; di < daftar.length; di++) {
        var item = daftar[di];
        var sp = item.spec;
        if (!sp && item.dinamis) sp = item.dinamis(tgl(item.hari));
        if (!sp) continue;
        var e = post(sp);
        if (item.tandaiSalah) jejakKoreksi = { entry: e, bulan: per };
        if (item.tandaiGanda) jejakPembalik = { entry: e, bulan: per };
        if (item.efek) item.efek();
      }

      /* --- pembalik atas nota ganda Oktober --------------------------- */
      if (m === 10 && jejakPembalik) {
        L.pembalik(buku, jejakPembalik.entry.id, per + '-16', {
          peran: 'akuntan', oleh: 'seed', sumber: 'seed', izinTerkunci: true,
          memo: 'Nota jasa ganda dibatalkan'
        });
      }

      /* --- koreksi atas entri listrik Agustus yang salah -------------- */
      if (m === 9 && jejakKoreksi) {
        L.koreksi(buku, jejakKoreksi.entry.id, {
          tgl: per + '-04',
          memo: 'Nilai tagihan listrik Agustus yang benar Rp 1.450.000',
          baris: [
            { akun: '5203', d: 1450000, k: 0, catatan: 'angka sesuai tagihan' },
            { akun: '1101', d: 0, k: 1450000 }
          ]
        }, { peran: 'akuntan', oleh: 'seed', sumber: 'seed', izinTerkunci: true });
      }

      /* --- PPN: setor kurang bayar masa sebelumnya -------------------- */
      /* Reads the LIVE balances of 1501 and 2104 as they stand at the end of the
       * previous month and offsets them. Nothing is assumed about what they
       * should be. */
      if (m >= 2) {
        var perLalu = D.tambahBulan(per, -1);
        var akhirLalu = D.akhirBulan(perLalu);
        var masukan = L.saldoAkun(buku, '1501', { sampai: akhirLalu }).saldo;
        var keluaran = L.saldoAkun(buku, '2104', { sampai: akhirLalu }).saldo;
        if (keluaran > 0 || masukan > 0) {
          var barisPpn = [], kurang = keluaran - masukan;
          if (kurang > 0) {
            /* keluaran > masukan: kompensasikan seluruh masukan, setor selisihnya */
            barisPpn.push({ akun: '2104', d: keluaran, k: 0, catatan: 'PPN keluaran masa ' + perLalu });
            if (masukan > 0) barisPpn.push({ akun: '1501', d: 0, k: masukan, catatan: 'dikompensasikan' });
            barisPpn.push({ akun: '1102', d: 0, k: kurang, catatan: 'setor PPN kurang bayar masa ' + perLalu });
          } else if (kurang < 0) {
            /* masukan > keluaran: hanya sebesar keluaran yang dikompensasikan,
             * sisa masukan dikreditkan ke masa berikutnya dan tetap jadi aset. */
            barisPpn.push({ akun: '2104', d: keluaran, k: 0, catatan: 'PPN keluaran masa ' + perLalu });
            barisPpn.push({ akun: '1501', d: 0, k: keluaran, catatan: 'kompensasi sebagian, sisa masukan dikreditkan ke masa berikutnya' });
          } else {
            barisPpn.push({ akun: '2104', d: keluaran, k: 0 });
            barisPpn.push({ akun: '1501', d: 0, k: masukan });
          }
          if (barisPpn.length >= 2 && keluaran > 0) {
            post({
              tgl: tgl(Math.min(15, hariAkhir)), jenis: 'umum',
              memo: 'Penyetoran dan kompensasi PPN masa ' + D.periodeNama(perLalu),
              baris: barisPpn
            });
          }
        }
      }

      /* --- PPh final UMKM 0,5% atas peredaran bruto bulan ini --------- */
      /* Computed AFTER every revenue entry of the month is in the book, including
       * the reversal of the duplicate — so the base is the month's net turnover,
       * which is what the 0,5% is actually levied on. */
      var brutoBulan = 0;
      var entriBulan = L.pilih(buku, { dari: D.awalBulan(per), sampai: D.akhirBulan(per) });
      var postBulan = L.postingan(entriBulan);
      D.AKUN.forEach(function (ak) {
        if (!ak.bruto) return;
        var r = postBulan[ak.kode];
        if (!r) return;
        brutoBulan = D.add(brutoBulan, D.NORMAL_TIPE[ak.tipe] === 'D' ? (r.d - r.k) : (r.k - r.d));
      });
      /* The Rp 500 juta that is not subject to tax for an orang pribadi is
       * consumed CUMULATIVELY by the earliest masa, so the instalment needs the
       * year's turnover BEFORE this month — which is exactly what brutoKumulatif
       * carries. On this book the exemption is used up in February, so January
       * owes nothing at all and February owes 0,5% of only the part that crosses
       * Rp 500 juta. Booking 0,5% of every rupiah instead overstated the year's
       * tax expense by exactly Rp 2.500.000. */
      var dasarPph = D.pphFinalDasar(brutoKumulatif, brutoBulan);
      var pph = dasarPph.kena > 0 ? D.pphFinal(dasarPph.kena) : 0;
      brutoKumulatif = D.add(brutoKumulatif, brutoBulan);
      if (pph > 0) {
        post({
          tgl: D.akhirBulan(per), jenis: 'umum',
          memo: 'PPh final UMKM 0,5% atas peredaran bruto ' + D.periodeNama(per) + ' (' + D.rupiah(brutoBulan) +
            (dasarPph.bebasDipakai > 0 ? ', bebas ' + D.rupiah(dasarPph.bebasDipakai) : '') +
            ', dasar kena ' + D.rupiah(dasarPph.kena) + ')',
          baris: [
            { akun: '5301', d: pph, k: 0, catatan: '0,5% × dasar kena, PP 55/2022' },
            { akun: '2105', d: 0, k: pph, catatan: 'terutang, disetor bulan berikutnya' }
          ]
        });
      }
      /* Previous month's PPh final actually paid. December's stays payable at
       * year end, which is why 2105 has a balance on the balance sheet. */
      if (m >= 2) {
        var perLalu2 = D.tambahBulan(per, -1);
        var utangPph = L.saldoAkun(buku, '2105', { sampai: D.akhirBulan(perLalu2) }).saldo;
        if (utangPph > 0) {
          post({
            tgl: tgl(Math.min(10, hariAkhir)), jenis: 'umum',
            memo: 'Penyetoran PPh final UMKM masa ' + D.periodeNama(perLalu2),
            baris: [
              { akun: '2105', d: utangPph, k: 0 },
              { akun: '1102', d: 0, k: utangPph, catatan: 'setor lewat bank persepsi' }
            ]
          });
        }
      }

      ringkasBulan.push({
        periode: per, dppPenjualan: dppBulan, hpp: hppBulan, belanja: belanja,
        brutoPajak: brutoBulan, pphFinal: pph,
        pphBebasDipakai: dasarPph.bebasDipakai, pphDasarKena: dasarPph.kena,
        brutoKumulatif: brutoKumulatif,
        persediaanAkhir: persediaan,
        listrik: listrik
      });

      if (m === 12) {
        akrual = registerAkrual(GAJI, BUNGA, listrik);
      }
    }

    /* ------------------------------------------------------- kunci periode */

    S.TERKUNCI.forEach(function (p) {
      L.tutupPeriode(buku, p, {
        peran: 'supervisor', oleh: 'supervisor (seed)', pada: D.akhirBulan(D.tambahBulan(p, 1)),
        catatan: 'Ditutup setelah pelaporan SPT Masa. Hanya supervisor yang boleh membukanya kembali.'
      });
    });

    return {
      buku: buku,
      profil: S.PROFIL,
      tahun: S.TAHUN, awal: S.AWAL, akhir: S.AKHIR, tglSaldoAwal: S.TGL_SALDO_AWAL,
      reg: { aset: aset, muka: muka, tangguh: tangguh, akrual: akrual, pinjaman: pinjaman },
      saldoLabaAwal: saldoLabaAwal,
      modalAwal: MODAL_AWAL,
      gajiBulanan: GAJI, bungaBulanan: BUNGA, angsuranBulanan: ANGSUR,
      pokokPinjamanAwal: pokokAwal, bagianLancarPinjamanAwal: bagianLancarAwal,
      ringkasBulan: ringkasBulan,
      jejak: { koreksi: jejakKoreksi, pembalik: jejakPembalik },
      seed: opts.seed === undefined ? S.SEED : opts.seed
    };
  };

  if (typeof module !== 'undefined' && module.exports) module.exports = S;
})(typeof self !== 'undefined' ? self : (typeof globalThis !== 'undefined' ? globalThis : this));
